version = 0.1

[default.deploy.parameters]
stack_name = "monitus-companion"
resolve_s3 = true
s3_prefix = "monitus-companion"
region = "ap-northeast-1"
confirm_changeset = false
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true

[default.global.parameters]
region = "ap-northeast-1"

# --- DEV ENVIRONMENT ---
[dev.deploy.parameters]
stack_name = "monitus-backend-dev"
resolve_s3 = true
parameter_overrides = "Stage=\"dev\""

# --- PROD ENVIRONMENT ---
[prod.deploy.parameters]
stack_name = "monitus-backend-prod"
resolve_s3 = true
parameter_overrides = "Stage=\"prod\""